//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUI.ConDmnsServis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConDmnsServis.IDmnsServis")]
    public interface IDmnsServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/Login", ReplyAction="http://tempuri.org/IDmnsServis/LoginResponse")]
        string Login(string email, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/Login", ReplyAction="http://tempuri.org/IDmnsServis/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string email, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/Urunler", ReplyAction="http://tempuri.org/IDmnsServis/UrunlerResponse")]
        string Urunler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/Urunler", ReplyAction="http://tempuri.org/IDmnsServis/UrunlerResponse")]
        System.Threading.Tasks.Task<string> UrunlerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/UrunGetir", ReplyAction="http://tempuri.org/IDmnsServis/UrunGetirResponse")]
        string UrunGetir(int urunId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/UrunGetir", ReplyAction="http://tempuri.org/IDmnsServis/UrunGetirResponse")]
        System.Threading.Tasks.Task<string> UrunGetirAsync(int urunId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/SiparisOlustur", ReplyAction="http://tempuri.org/IDmnsServis/SiparisOlusturResponse")]
        string SiparisOlustur(string siparisler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/SiparisOlustur", ReplyAction="http://tempuri.org/IDmnsServis/SiparisOlusturResponse")]
        System.Threading.Tasks.Task<string> SiparisOlusturAsync(string siparisler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/Kupon", ReplyAction="http://tempuri.org/IDmnsServis/KuponResponse")]
        bool Kupon(int kisiId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmnsServis/Kupon", ReplyAction="http://tempuri.org/IDmnsServis/KuponResponse")]
        System.Threading.Tasks.Task<bool> KuponAsync(int kisiId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDmnsServisChannel : MvcUI.ConDmnsServis.IDmnsServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DmnsServisClient : System.ServiceModel.ClientBase<MvcUI.ConDmnsServis.IDmnsServis>, MvcUI.ConDmnsServis.IDmnsServis {
        
        public DmnsServisClient() {
        }
        
        public DmnsServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DmnsServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmnsServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmnsServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string email, string sifre) {
            return base.Channel.Login(email, sifre);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string email, string sifre) {
            return base.Channel.LoginAsync(email, sifre);
        }
        
        public string Urunler() {
            return base.Channel.Urunler();
        }
        
        public System.Threading.Tasks.Task<string> UrunlerAsync() {
            return base.Channel.UrunlerAsync();
        }
        
        public string UrunGetir(int urunId) {
            return base.Channel.UrunGetir(urunId);
        }
        
        public System.Threading.Tasks.Task<string> UrunGetirAsync(int urunId) {
            return base.Channel.UrunGetirAsync(urunId);
        }
        
        public string SiparisOlustur(string siparisler) {
            return base.Channel.SiparisOlustur(siparisler);
        }
        
        public System.Threading.Tasks.Task<string> SiparisOlusturAsync(string siparisler) {
            return base.Channel.SiparisOlusturAsync(siparisler);
        }
        
        public bool Kupon(int kisiId) {
            return base.Channel.Kupon(kisiId);
        }
        
        public System.Threading.Tasks.Task<bool> KuponAsync(int kisiId) {
            return base.Channel.KuponAsync(kisiId);
        }
    }
}
